name: CI build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: |
          3.1.x
          5.0.x
    - run: dotnet build
